### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by takako0420** [takako0420/furima-37051#20]
## URL
https://furima-37051.herokuapp.com/

## Basic認証のIDとパスワード
ID : admin
pass : 2222

## 出品者用のメールアドレスとパスワード
email : 1@com
pass : 111qqq

## 購入者用のメールアドレスとパスワード
email : 2@com
pass : 111qqq

**Comment by miyu-yamamoto** [comment]
@takako0420 さん、ご提出いただきありがとうございます。
動作の確認をしたところ、修正していただきたい箇所がございました。
以下、ご確認をお願いします！

[修正依頼箇所]
- [x] **カテゴリーは、「---、メンズ、レディース、ベビー・キッズ、インテリア・住まい・小物、本・音楽・ゲーム、おもちゃ・ホビー・グッズ、家電・スマホ・カメラ、スポーツ・レジャー、ハンドメイド、その他」の11項目が表示されること**
現在12項目表示されておりますので、「インテリア・住まい・小物」を一つのカテゴリにまとめましょう
<img width="383" alt="スクリーンショット 2021-11-10 17 43 45" src="https://user-images.githubusercontent.com/59544869/141079742-0455be49-ca53-446a-aee0-35126b88303c.png">

修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by takako0420** [comment]
ご指摘ありがとうございます！
修正しました！

**Comment by yutomentors** [comment]
恐れ入りますが、いただいたプルリクエストは、完了報告用のプルリクエストのように見受けられます。
こちらはこれまでの機能毎のプルリクエストとは、フォーム及び提出先が異なっております。
お手数おかけいたしますが、カリキュラム内にリンクが貼られている「フリマアプリ完了報告フォーム」より再度フォームのご提出のほどよろしくお願いいたします。
もしご不明点がございましたら、コネクトにてご質問のほどよろしくお願いいたします。

**Comment by snkw-works** [comment]
@takako0420 さん、お待たせいたしました。フリマアプリ達成要件分の開発お疲れ様でした！
正常に動作することが確認できました！ **LGTM** です！　
おめでとうございます🎉

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願いいたします。**

**※Github上の最終課題の履歴はここまで頑張ってきた証です。削除せず大切に保管するようにしましょう。**

ここまで培ってきた知識や学びを活かして、これからは下記例のようなさらなる学習に取り組みましょう！

#### ＜今後の学習例＞
```
・フリマアプリ追加実装
・オリジナルアプリ開発
・今まで学んできた言語あるいは新言語の学習　等
```
今後の学習方針や学習計画については、担当ライフコーチまでお気軽にご相談くださいませ。

また、以下提出物に関するリマインドです。

#### ＜提出物＞
```
・最終課題説明文（フリマアプリ達成要件および、追加実装内容にて作成をお願いいたします）
・要件定義（追加実装あるいは、オリジナルアプリの内容で作成をお願いいたします）
```
※提出期日については、最終課題開始時に配布した下記動画にてご確認いただきますようお願いいたします。

#### ＜最終課題に関する締め切りについての動画＞
https://master.tech-camp.in/v2/curriculums/6852

今後の流れに関して、もしご不明点がございましたら、担当ライフコーチまでお気兼ねなくお申し付けくださいませ。
![最終課題終了_おめでとう画像_new1](https://user-images.githubusercontent.com/54050089/141217824-1eef624c-f635-40b8-bca8-0b761000a6ab.png)
